### ISSUE TITLE
Already had a fully capable and equipped msys64-ucrt......

### ISSUE THREAD

**Issue by AD5GB** [ccmywish/rbenv-for-windows#10]
It was already there.  On the path and in the environment for the taking.  Yet you felt you had to install your own.  Thanks for bricking my box.  This is expressly why I avoid Windows ANYTHING at ALL costs!  Having been a UNIX/Linux software developer/engineer for 24 years now, all I can say is FIX YOUR SHIT!

**Comment by ccmywish** [comment]
Hi @AD5GB 

Sorry for annoying you with the redundant MSYS2 installation.

I've re-contemplated this. I still think we should download our own MSYS2, and not reuse user's own.

Because the `RubyInstaller2 bundled MSYS2` has everything ready to build CRuby gems, battle-tested by upstream. Honestly,   it may bundle with some homebrewed tools only targeting to support CRuby on Windows.

However, we don't know what exists in one user's own MSYS2, it may lack something. Is thit really fully capable? We are not sure and untested. 

And there's another reason: `ridk` is in Ruby commands runtime. When any Ruby command starts, it will search
MSYS2 existence, hence severely affects the startup time if not quickly checked.
