### ISSUE TITLE
iwr command fails trying to install on windows powershell

### ISSUE THREAD

**Issue by svashish305** [ccmywish/rbenv-for-windows#14]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/15891085/224940473-9ebcea27-a853-4daf-8b27-2b0585dd55d6.png">
On checking around it seems powershell doesn't use TLS 1.2 by default, but also checked changing that manually isn't recommended.
Is there any other alternate way to install rbenv-for-windows?

**Comment by ccmywish** [comment]
Hi @svashish305 

Sorry I'm not sure what the error indicated, is it related to TLS? My machine doesn't encounter this. What's your version of `PowerShell`?  I think you could try these two methods to install:

1.  Run `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser` in your terminal, and then run the installation script again by `iwr -useb "https://github.com/ccmywish/rbenv-for-windows/raw/main/tools/install.ps1" | iex`.

2. Or just copy the script content https://github.com/ccmywish/rbenv-for-windows/blob/main/tools/install.ps1, save it and directly run it.

The second method can make sure you install successfully, but I suggest you try the first method because I think it's the cause of the issue.

**Comment by svashish305** [comment]
hey @ccmywish , thanks, I already tried step 1 as it was one of listed pre-requisites. I'm using powershell on windows 11.
Step 2 works.
