### ISSUE TITLE
& "$env:RBENV_ROOT\rbenv\bin\rbenv.ps1" init  不能正确执行

### ISSUE THREAD

**Issue by guojhq** [ccmywish/rbenv-for-windows#7]
![image](https://user-images.githubusercontent.com/3446860/211701048-22771f37-b34c-4365-85d2-115e1cf7db34.png)
![image](https://user-images.githubusercontent.com/3446860/211701083-b2d25b69-75a9-419c-9456-0f650e0a52ea.png)

**Comment by ccmywish** [comment]
哦，我才看到，原链接你这边也下载不了。我这边来排查下。

**Comment by ccmywish** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/63459097/211703499-2a6a1240-d5a3-43fd-a82b-08d82fd1fc1e.png">

我这边没啥问题。可能你需要检查下你那边的网络问题，如还是无法工作，请继续反馈。

**Comment by guojhq** [comment]
好吧 我看下，谢谢

**Comment by guojhq** [comment]
用浏览器访问 https://mirror.sjtu.edu.cn/github-release/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.0-1/rubyinstaller-devkit-3.2.0-1-x64.exe 这个链接，跳转到其他URL了，是不是这个原因了，我的浏览器能下载
![image](https://user-images.githubusercontent.com/3446860/212229489-97fa301b-97c0-4bd5-a182-884e093b556d.png)

**Comment by ccmywish** [comment]
了解了，我再研究下。你先试试不用镜像，看看原来的链接(`RubyIntsaller.org`那个)你能用 `rbenv` 下载安装吗？

**Comment by guojhq** [comment]
原来的链接可以，只是需要我访问github，可能有时候会网络连接失败吧
![image](https://user-images.githubusercontent.com/3446860/212231214-977d8227-349b-45ec-961d-100ee7be0c5c.png)

**Comment by ccmywish** [comment]
我这边提供两个方案供您解决：

1. 麻烦看下你的 `$PSVersionTable` 以获得你使用的PowerShell版本。建议您使用 `PowerShell core 7.2` 以上。因为从开发到现在，`308`都能正常的处理。通过升级，您的问题应该可以完全得到解决。

2.  不升级`PowerShell`. 但是在下图这个文件所示位置添加这一行代码，然后重新运行试试看。我所用的`PowerShell`运行不到这儿来，所以在我的机器上无法判断是否能解决你的问题，抱歉。
```PowerShell
[System.Net.HttpStatusCode]::PermanentRedirect  # HTTP 308
```
<img width="501" alt="image" src="https://user-images.githubusercontent.com/63459097/212323228-4f9ee3b7-4223-4434-a4fb-00ac7f9f4722.png">

**Comment by ricardoduarte** [comment]
Hello @ccmywish and @guojhq,

I'm having the same issue. If there is a solution for this, can you please post it here in English?

**Comment by ccmywish** [comment]
Hi @ricardoduarte

First, I want to ask that, do you try to install directly (that is not via mirror)? If so, the issue you meet is same as #8

I don't know if the solution above is useful to @guojhq, but here I can translate the method for you:

---

I offer two schemes for your reference:

1. Please look at your `$PSVersionTable` to get the version of `PowerShell` you are using. It is recommended that you use PowerShell core 7.2 or higher. Since the development until now, 308 can be processed normally. With the upgrade, your problem should be completely resolved.

2. Do not upgrade PowerShell. But add this line of code in the file shown below and try running it again. My PowerShell doesn't run here, so I can't tell if I can solve your problem on my machine. Sorry.

```PowerShell
[System.Net.HttpStatusCode]::PermanentRedirect  # HTTP 308
```
![code](https://user-images.githubusercontent.com/63459097/212323228-4f9ee3b7-4223-4434-a4fb-00ac7f9f4722.png)

**Comment by ricardoduarte** [comment]
@ccmywish Now I noticed what was causing my problem. I copied the Powershell config from the project README and didn't delete the line to use a chinese mirror 🤦‍♂️ 

Now it is working fine, thanks for your help.

**Comment by ccmywish** [comment]
Haha, also good to know it's not a difficult issue for maintenance work 😂

**Comment by ricardoduarte** [comment]
@ccmywish My Powershell version is 5.1

**Comment by ccmywish** [comment]
Thanks for your information ❤️

**Comment by ccmywish** [comment]
I will close this issue. If there are still any questions, please feel free to come back and ask.

**Comment by ccmywish** [comment]
@guojhq 

I've fixed it now for `PowerShell v5.x series`. See https://github.com/ccmywish/rbenv-for-windows/issues/18

此问题属于`PowerShell v5.x 系列`，现已修复，感谢反馈👍 见 https://github.com/ccmywish/rbenv-for-windows/issues/18
